// CyberRx — framework catalog loader (Phase 4a)
//
// Parses authoritative OSCAL and emits SQL that upserts framework + control rows
// into the Phase 1 schema (public.frameworks / public.controls). Catalogs load
// VERBATIM from their authoritative sources — IDs and titles are never invented.
//
// Source of truth (public, canonical):
//   NIST SP 800-53 Rev 5 — usnistgov/oscal-content (OSCAL JSON)
//
// Usage:
//   node load_catalogs.mjs <path-to-800-53-oscal.json> > catalogs.sql
//   psql "$DATABASE_URL" -f catalogs.sql        # local Postgres or Supabase
//
// SOC 2 control TITLES are licensed and must be loaded from their licensed
// distributions; this loader registers the frameworks and is ready to ingest
// their control rows the same way.

import { readFileSync } from 'node:fs'

const q = (s) => (s == null ? 'null' : `'${String(s).replace(/'/g, "''")}'`)

function emitFrameworks() {
  const rows = [
    ['CSF_2_0', 'NIST Cybersecurity Framework 2.0', '2.0', 'https://www.nist.gov/cyberframework'],
    ['NIST_800_53', 'NIST SP 800-53', 'Rev 5', 'https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final'],
    ['SOC_2', 'AICPA SOC 2 (Trust Services Criteria)', '2017 (rev. 2022)', 'https://www.aicpa.org'],
  ]
  const lines = rows.map(
    ([key, name, version, url]) =>
      `insert into public.frameworks (key, name, version, source_url) values (${q(key)}, ${q(name)}, ${q(version)}, ${q(url)}) on conflict (key) do update set name=excluded.name, version=excluded.version, source_url=excluded.source_url;`,
  )
  return lines.join('\n')
}

// 800-53 OSCAL: catalog.groups[] (families) → controls[] (base) → controls[] (enhancements)
function emit80053(oscalPath) {
  const cat = JSON.parse(readFileSync(oscalPath, 'utf8')).catalog
  const out = []
  out.push(
    `\n-- NIST 800-53 Rev 5 controls (verbatim from OSCAL: ${cat.metadata.title.replace(/'/g, '')})`,
  )
  out.push(
    `with fw as (select id from public.frameworks where key='NIST_800_53')`,
  )
  const values = []
  for (const g of cat.groups || []) {
    for (const c of g.controls || []) {
      values.push(`((select id from fw), ${q(c.id.toUpperCase())}, ${q(c.title)}, null)`)
      for (const e of c.controls || []) {
        values.push(`((select id from fw), ${q(e.id.toUpperCase())}, ${q(e.title)}, ${q(c.id.toUpperCase())})`)
      }
    }
  }
  out.push(
    `insert into public.controls (framework_id, control_id, title, parent_control_id)\nvalues\n${values.join(',\n')}\non conflict (framework_id, control_id) do update set title=excluded.title;`,
  )
  return { sql: out.join('\n'), count: values.length }
}

const oscalPath = process.argv[2]
if (!oscalPath) {
  console.error('usage: node load_catalogs.mjs <800-53-oscal.json>')
  process.exit(1)
}

let sql = '-- CyberRx framework catalogs (generated by load_catalogs.mjs)\nbegin;\n'
sql += emitFrameworks() + '\n'
const r53 = emit80053(oscalPath)
sql += r53.sql + '\n'
sql += 'commit;\n'
process.stdout.write(sql)
process.stderr.write(`emitted ${r53.count} NIST 800-53 control rows\n`)
