// CyberRx — deterministic control scorer (Phase 4b)
//
// The engine OWNS the truth: CMMI maturity, confidence, and status are COMPUTED
// from evidence — never generated by an LLM. Given the same inputs it always
// returns the same outputs (pure, no randomness, no network). An LLM may later
// PROPOSE a maturity *with a citation*, but an analyst reviews and this function
// does the math.

export type ControlSignal = {
  /** Evidence signal id (e.g. a connector/control check). */
  id: string
  /** Is the expected evidence present for this control? */
  present: boolean
  /** Age of the evidence in hours (used for freshness). */
  ageHours: number
}

export type Cmmi = 0 | 1 | 2 | 3 | 4 | 5
export type ControlStatus = 'no_data' | 'fail' | 'partial' | 'pass'

export type ControlScore = {
  cmmi: Cmmi
  status: ControlStatus
  /** 0..1 — mechanical, from coverage breadth and freshness. */
  confidence: number
  /** 0..1 — fraction of expected evidence present. */
  coverage: number
  /** 0..1 — average recency of present evidence. */
  freshness: number
}

// Evidence older than this contributes no freshness.
const FRESH_WINDOW_HOURS = 24 * 30 // 30 days

const r2 = (n: number) => Math.round(n * 100) / 100

/** Score a single control from its evidence signals. Deterministic. */
export function scoreControl(signals: ControlSignal[]): ControlScore {
  const total = signals.length
  if (total === 0) {
    return { cmmi: 0, status: 'no_data', confidence: 0, coverage: 0, freshness: 0 }
  }
  const present = signals.filter((s) => s.present)
  const coverage = present.length / total
  const freshness =
    present.length === 0
      ? 0
      : present.reduce((a, s) => a + Math.max(0, 1 - s.ageHours / FRESH_WINDOW_HOURS), 0) / present.length

  // CMMI is driven by coverage, dampened by how stale the evidence is.
  const raw = coverage * 5 * (0.6 + 0.4 * freshness)
  const cmmi = Math.max(0, Math.min(5, Math.round(raw))) as Cmmi

  // Confidence is mechanical — breadth × recency — not a vibe.
  const confidence = r2(coverage * (0.5 + 0.5 * freshness))

  const status: ControlStatus =
    coverage === 0 ? 'no_data' : coverage < 0.5 ? 'fail' : coverage < 0.9 ? 'partial' : 'pass'

  return { cmmi, status, confidence, coverage: r2(coverage), freshness: r2(freshness) }
}

/** Roll up child control scores into a category/function CMMI (evidence-weighted). */
export function rollup(scores: ControlScore[]): { cmmi: Cmmi; confidence: number } {
  const scored = scores.filter((s) => s.status !== 'no_data')
  if (scored.length === 0) return { cmmi: 0, confidence: 0 }
  const cmmi = Math.round(scored.reduce((a, s) => a + s.cmmi, 0) / scored.length) as Cmmi
  const confidence = r2(scored.reduce((a, s) => a + s.confidence, 0) / scored.length)
  return { cmmi, confidence }
}
