// ─────────────────────────────────────────────────────────────────────────────
// Nerion — production-realistic demo dataset: one industry leader per sector.
//
// Financials are grounded in each company's most recent public filings (FY2024 /
// FY2025 10-K / annual report) and are ILLUSTRATIVE — rounded, and cyber-specific
// figures (appetite, budget, insurance, risk exposures, inventory) are modelled to
// be sector-plausible, not disclosed. Every money value is a RAW dollar integer
// (the onboarding "unit" multiplier is already applied). See README for sources.
//
// 8 sectors across the cockpit's industry buckets:
//   health · tech · fin · retail · gov · mfg · energy · telecom
// ─────────────────────────────────────────────────────────────────────────────

const B = 1e9, M = 1e6, K = 1e3;

export const ORGS = [
  // ═══════════════════════════ 1 · HEALTHCARE ═══════════════════════════
  {
    key: 'unitedhealth',
    org_name: 'UnitedHealth Group',
    industry: 'Healthcare',            // → health
    regions: ['US'],
    currency: 'USD',
    story: 'Largest U.S. health payer & services group (Optum + UnitedHealthcare). The 2024 Change Healthcare ransomware attack is the defining sector scenario — a clearinghouse compromise that halted claims nationwide.',
    financials: { revenue: 400.3 * B, operatingIncome: 32.3 * B, netIncome: 14.4 * B, enterpriseValue: 374 * B, sharesOutstanding: 920 * M },
    appetite: 500 * M, budget: 750 * M, dataRecords: 152 * M,
    principalRisks: { creditMarket: 15 * B, operational: 9 * B, thirdParty: 5 * B, compliance: 4 * B },
    insurance: { limit: 200 * M, premium: 12 * M, retention: 25 * M, renewal: '2026-10-01' },
    governance: { committee: 'Risk Committee', cadence: 'Quarterly', cisoReportsTo: 'CEO', boardExpertise: 'Yes', ermIntegrated: 'Yes',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-02-15', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 20, decisioning: 'Yes', framework: 'NIST AI RMF', policy: 'Board-approved', euAiAct: 'Not in scope', inventory: 'Yes — inventoried' },
    growth: { pipelineUsd: 8 * B, reviewBeforeWks: '6', reviewNowWks: '2', dealsGated: '14', trustReviews: '20', certs: ['HITRUST', 'SOC 2 Type II', 'ISO 27001'] },
    seatNames: { ceo: 'A. Whitmore', cfo: 'J. Rehnquist', ciso: 'S. Patel', cio: 'D. Okonkwo', clo: 'M. Delgado', cro: 'R. Halvorsen' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'proofpoint', 'wiz', 'rubrik', 'servicenow', 'onetrust', 'servicenow_grc', 'github'],
    processes: [
      { name: 'Claims processing & payment', revenue: '$200B', rto: '4', data: 'PHI, Financial', criticality: 'Critical', tx: '12000000', tolerance: '$8M' },
      { name: 'Pharmacy benefit management (OptumRx)', revenue: '$120B', rto: '6', data: 'PHI, PCI', criticality: 'Critical', tx: '5000000', tolerance: '$5M' },
      { name: 'Care delivery & clinical (Optum Health)', revenue: '$100B', rto: '8', data: 'PHI', criticality: 'Critical', tx: '2000000', tolerance: '$3M' },
      { name: 'Eligibility & enrollment', revenue: '$40B', rto: '12', data: 'PHI, PII', criticality: 'High', tx: '900000', tolerance: '$1.5M' },
      { name: 'Provider network payments', revenue: '$30B', rto: '12', data: 'Financial', criticality: 'High', tx: '600000', tolerance: '$1M' },
    ],
    apps: [
      { name: 'Change Healthcare clearinghouse', host: 'internet-facing', data: 'PHI, Financial', vendor: 'Optum / Change Healthcare', eol: 'no', recovery: '48', tx: '12000000', value: '$120M', processes: ['Claims processing & payment', 'Provider network payments'] },
      { name: 'Claims adjudication DB', host: 'database on-prem', data: 'PHI, Financial', vendor: 'Oracle', eol: 'no', recovery: '24', tx: '12000000', value: '$90M', processes: ['Claims processing & payment'] },
      { name: 'OptumRx pharmacy platform', host: 'application cloud', data: 'PHI, PCI', vendor: 'AWS', eol: 'no', recovery: '12', tx: '5000000', value: '$60M', processes: ['Pharmacy benefit management (OptumRx)'] },
      { name: 'Member portal', host: 'internet-facing web', data: 'PHI, PII', vendor: 'Azure', eol: 'no', recovery: '8', tx: '3000000', value: '$18M', processes: ['Eligibility & enrollment', 'Care delivery & clinical (Optum Health)'] },
      { name: 'EDI gateway', host: 'internet-facing', data: 'PHI', vendor: 'IBM', eol: 'yes', recovery: '24', tx: '4000000', value: '$22M', processes: ['Claims processing & payment'] },
      { name: 'Clinical data warehouse', host: 'database on-prem', data: 'PHI', vendor: 'Snowflake', eol: 'no', recovery: '36', tx: '500000', value: '$30M', processes: ['Care delivery & clinical (Optum Health)'] },
    ],
    risks: [
      { title: 'Ransomware on claims clearinghouse', severity: 'Critical', asset: 'Change Healthcare clearinghouse', exposure: '$180M', status: 'open' },
      { title: 'PHI exfiltration from claims database', severity: 'Critical', asset: 'Claims adjudication DB', exposure: '$95M', status: 'open' },
      { title: 'Third-party breach via pharmacy cloud', severity: 'High', asset: 'OptumRx pharmacy platform', exposure: '$40M', status: 'open' },
      { title: 'Credential stuffing on member portal', severity: 'High', asset: 'Member portal', exposure: '$25M', status: 'open' },
      { title: 'Legacy EDI gateway exploit', severity: 'High', asset: 'EDI gateway', exposure: '$22M', status: 'open' },
    ],
    initiatives: [
      { name: 'Segment & isolate clearinghouse', owner: 'CISO', cost: '$28M', roi: '22×', status: 'in progress', engagement: 'gate' },
      { name: 'Zero-trust for PHI systems', owner: 'CISO', cost: '$18M', roi: '15×', status: 'in progress', engagement: 'design' },
      { name: 'Third-party risk program', owner: 'CRO', cost: '$9M', roi: '8×', status: 'planned', engagement: 'design' },
      { name: 'Immutable backup & rapid recovery', owner: 'CIO', cost: '$14M', roi: '19×', status: 'in progress', engagement: 'gate' },
    ],
    strategicInitiatives: [
      { name: 'Optum AI clinical documentation', type: 'AI product or feature', valueUsd: 2.5 * B, horizon: 'This year' },
      { name: 'Value-based care expansion', type: 'Market / geographic expansion', valueUsd: 5 * B, horizon: 'Next 12–24 months' },
      { name: 'Change Healthcare re-platform', type: 'Cloud platform or migration', valueUsd: 1.2 * B, horizon: 'This year' },
    ],
    frameworks: ['HIPAA Security Rule', 'HITRUST CSF', 'NIST CSF 2.0', 'SOC 2'],
    docMaturity: 4,
  },

  // ═══════════════════════════ 2 · TECHNOLOGY ═══════════════════════════
  {
    key: 'microsoft',
    org_name: 'Microsoft Corporation',
    industry: 'Technology / SaaS',      // → tech
    regions: ['US', 'EU', 'Global'],
    currency: 'USD',
    story: 'Global platform & cloud provider (Azure, M365, GitHub). Crown jewels are source code, signing infrastructure, and the identity plane — nation-state targeting (Midnight Blizzard) and supply-chain integrity dominate the risk picture.',
    financials: { revenue: 245.1 * B, operatingIncome: 109.4 * B, netIncome: 88.1 * B, enterpriseValue: 3.0e12, sharesOutstanding: 7.43 * B },
    appetite: 1 * B, budget: 2 * B, dataRecords: 1.4 * B,
    principalRisks: { creditMarket: 20 * B, operational: 14 * B, thirdParty: 8 * B, compliance: 10 * B },
    insurance: { limit: 500 * M, premium: 25 * M, retention: 100 * M, renewal: '2026-09-01' },
    governance: { committee: 'Audit Committee', cadence: 'Every board meeting', cisoReportsTo: 'CEO', boardExpertise: 'Yes', ermIntegrated: 'Yes',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-04-10', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 120, decisioning: 'Yes', framework: 'Both', policy: 'Board-approved', euAiAct: 'Yes — high-risk system', inventory: 'Yes — inventoried' },
    growth: { pipelineUsd: 40 * B, reviewBeforeWks: '4', reviewNowWks: '1', dealsGated: '30', trustReviews: '60', certs: ['SOC 2 Type II', 'ISO 27001', 'FedRAMP High', 'ISO 42001'] },
    seatNames: { ceo: 'S. Nadeau', cfo: 'A. Hoodbhoy', ciso: 'B. Arsenault', cio: 'N. Lundgren', clo: 'B. Smithe', cro: 'K. Osei' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'wiz', 'github', 'rubrik', 'servicenow', 'onetrust', 'servicenow_grc', 'recordedfuture'],
    processes: [
      { name: 'Azure cloud platform operations', revenue: '$110B', rto: '2', data: 'PII, Confidential, IP', criticality: 'Critical', tx: '50000000', tolerance: '$20M' },
      { name: 'M365 productivity & identity', revenue: '$80B', rto: '2', data: 'PII, Confidential', criticality: 'Critical', tx: '40000000', tolerance: '$15M' },
      { name: 'Developer platform (GitHub)', revenue: '$20B', rto: '4', data: 'IP, Source Code', criticality: 'Critical', tx: '8000000', tolerance: '$6M' },
      { name: 'Gaming & consumer (Xbox)', revenue: '$22B', rto: '8', data: 'PII, PCI', criticality: 'High', tx: '5000000', tolerance: '$3M' },
      { name: 'Commercial licensing & billing', revenue: '$13B', rto: '12', data: 'Financial, PII', criticality: 'High', tx: '1000000', tolerance: '$2M' },
    ],
    apps: [
      { name: 'Entra ID identity plane', host: 'internet-facing', data: 'PII, Credentials', vendor: 'Microsoft', eol: 'no', recovery: '2', tx: '80000000', value: '$200M', processes: ['M365 productivity & identity', 'Azure cloud platform operations'] },
      { name: 'Code-signing infrastructure', host: 'application on-prem', data: 'IP, CUI, Signing Keys', vendor: 'Microsoft', eol: 'no', recovery: '4', tx: '100000', value: '$150M', processes: ['Developer platform (GitHub)', 'Azure cloud platform operations'] },
      { name: 'Source-code repositories (GitHub)', host: 'internet-facing', data: 'IP, Source Code', vendor: 'GitHub', eol: 'no', recovery: '4', tx: '8000000', value: '$120M', processes: ['Developer platform (GitHub)'] },
      { name: 'Azure control plane', host: 'internet-facing', data: 'Confidential, PII', vendor: 'Microsoft', eol: 'no', recovery: '2', tx: '50000000', value: '$180M', processes: ['Azure cloud platform operations'] },
      { name: 'Customer support case system', host: 'application cloud', data: 'PII, Confidential', vendor: 'Salesforce', eol: 'no', recovery: '12', tx: '2000000', value: '$14M', processes: ['Commercial licensing & billing'] },
      { name: 'Xbox Live services', host: 'internet-facing web', data: 'PII, PCI', vendor: 'Microsoft', eol: 'no', recovery: '8', tx: '5000000', value: '$12M', processes: ['Gaming & consumer (Xbox)'] },
    ],
    risks: [
      { title: 'Nation-state intrusion into identity plane', severity: 'Critical', asset: 'Entra ID identity plane', exposure: '$220M', status: 'open' },
      { title: 'Code-signing key compromise', severity: 'Critical', asset: 'Code-signing infrastructure', exposure: '$160M', status: 'open' },
      { title: 'Source-code theft / supply-chain implant', severity: 'Critical', asset: 'Source-code repositories (GitHub)', exposure: '$110M', status: 'open' },
      { title: 'Azure control-plane privilege escalation', severity: 'High', asset: 'Azure control plane', exposure: '$70M', status: 'open' },
      { title: 'Support-system token abuse', severity: 'High', asset: 'Customer support case system', exposure: '$18M', status: 'open' },
    ],
    initiatives: [
      { name: 'Secure Future Initiative — identity hardening', owner: 'CISO', cost: '$120M', roi: '18×', status: 'in progress', engagement: 'gate' },
      { name: 'Signing-key HSM & isolation', owner: 'CISO', cost: '$45M', roi: '14×', status: 'in progress', engagement: 'gate' },
      { name: 'Supply-chain integrity (SLSA) rollout', owner: 'CTO', cost: '$30M', roi: '11×', status: 'in progress', engagement: 'design' },
      { name: 'Tenant isolation & token-theft defense', owner: 'CISO', cost: '$28M', roi: '13×', status: 'planned', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'Copilot enterprise expansion', type: 'AI product or feature', valueUsd: 10 * B, horizon: 'This year' },
      { name: 'Sovereign cloud (EU) buildout', type: 'Market / geographic expansion', valueUsd: 6 * B, horizon: 'Next 12–24 months' },
      { name: 'Activision integration', type: 'Acquisition / M&A', valueUsd: 3 * B, horizon: 'This year' },
    ],
    frameworks: ['NIST CSF 2.0', 'ISO 27001', 'SOC 2', 'FedRAMP', 'EU AI Act', 'ISO 42001'],
    docMaturity: 5,
  },

  // ═══════════════════════════ 3 · FINANCIAL SERVICES ═══════════════════════════
  {
    key: 'jpmorgan',
    org_name: 'JPMorgan Chase & Co.',
    industry: 'Financial services',     // → fin
    regions: ['US', 'EU', 'UK'],
    currency: 'USD',
    story: 'Largest U.S. bank by assets. Crown jewels are the payments rails, trading & settlement, and customer financial data. SEC 4-business-day disclosure, DORA, and wire/payment fraud (BEC) dominate.',
    financials: { revenue: 177.6 * B, operatingIncome: 61 * B, netIncome: 58.5 * B, enterpriseValue: 670 * B, sharesOutstanding: 2.86 * B },
    appetite: 750 * M, budget: 1.5 * B, dataRecords: 80 * M,
    principalRisks: { creditMarket: 210 * B, operational: 45 * B, thirdParty: 18 * B, compliance: 25 * B },
    insurance: { limit: 400 * M, premium: 20 * M, retention: 75 * M, renewal: '2026-12-01' },
    governance: { committee: 'Risk Committee', cadence: 'Every board meeting', cisoReportsTo: 'CRO / Chief Risk', boardExpertise: 'Yes', ermIntegrated: 'Yes',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-03-20', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 60, decisioning: 'Yes', framework: 'NIST AI RMF', policy: 'Board-approved', euAiAct: 'Yes — limited-risk', inventory: 'Yes — inventoried' },
    growth: { pipelineUsd: 12 * B, reviewBeforeWks: '5', reviewNowWks: '2', dealsGated: '22', trustReviews: '35', certs: ['SOC 2 Type II', 'ISO 27001', 'PCI DSS'] },
    seatNames: { ceo: 'J. Dammon', cfo: 'J. Baraka', ciso: 'P. Cavanaghe', cio: 'L. Deyo', clo: 'S. Roskind', cro: 'A. Beacom' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'proofpoint', 'sap', 'wiz', 'rubrik', 'servicenow', 'onetrust', 'recordedfuture', 'servicenow_grc'],
    processes: [
      { name: 'Wholesale payments & wire', revenue: '$45B', rto: '1', data: 'Financial, PII', criticality: 'Critical', tx: '10000000', tolerance: '$25M' },
      { name: 'Markets — trading & settlement', revenue: '$50B', rto: '2', data: 'Financial, MNPI', criticality: 'Critical', tx: '8000000', tolerance: '$30M' },
      { name: 'Consumer & community banking', revenue: '$55B', rto: '4', data: 'PII, PCI, Financial', criticality: 'Critical', tx: '60000000', tolerance: '$12M' },
      { name: 'Asset & wealth management', revenue: '$20B', rto: '8', data: 'PII, Financial', criticality: 'High', tx: '2000000', tolerance: '$4M' },
      { name: 'Card & merchant services', revenue: '$8B', rto: '6', data: 'PCI, Financial', criticality: 'High', tx: '40000000', tolerance: '$6M' },
    ],
    apps: [
      { name: 'Fedwire / RTGS payment gateway', host: 'internet-facing', data: 'Financial, PII', vendor: 'In-house', eol: 'no', recovery: '2', tx: '10000000', value: '$300M', processes: ['Wholesale payments & wire'] },
      { name: 'Trade settlement engine', host: 'application on-prem', data: 'Financial, MNPI', vendor: 'In-house', eol: 'no', recovery: '2', tx: '8000000', value: '$260M', processes: ['Markets — trading & settlement'] },
      { name: 'Core deposit ledger', host: 'database on-prem', data: 'PII, Financial', vendor: 'IBM', eol: 'no', recovery: '4', tx: '60000000', value: '$180M', processes: ['Consumer & community banking'] },
      { name: 'Online & mobile banking', host: 'internet-facing web', data: 'PII, PCI, Financial', vendor: 'In-house', eol: 'no', recovery: '4', tx: '50000000', value: '$120M', processes: ['Consumer & community banking'] },
      { name: 'Card authorization switch', host: 'internet-facing', data: 'PCI, Financial', vendor: 'Visa/MC', eol: 'no', recovery: '2', tx: '40000000', value: '$140M', processes: ['Card & merchant services'] },
      { name: 'Wealth advisory platform', host: 'application cloud', data: 'PII, Financial', vendor: 'AWS', eol: 'no', recovery: '8', tx: '2000000', value: '$20M', processes: ['Asset & wealth management'] },
    ],
    risks: [
      { title: 'Wire-fraud / payment-rail compromise', severity: 'Critical', asset: 'Fedwire / RTGS payment gateway', exposure: '$260M', status: 'open' },
      { title: 'Settlement engine outage / manipulation', severity: 'Critical', asset: 'Trade settlement engine', exposure: '$210M', status: 'open' },
      { title: 'Core-ledger data breach', severity: 'Critical', asset: 'Core deposit ledger', exposure: '$140M', status: 'open' },
      { title: 'Cardholder-data (PCI) exfiltration', severity: 'High', asset: 'Card authorization switch', exposure: '$85M', status: 'open' },
      { title: 'Account-takeover on mobile banking', severity: 'High', asset: 'Online & mobile banking', exposure: '$55M', status: 'open' },
    ],
    initiatives: [
      { name: 'Payments fraud-detection uplift', owner: 'CISO', cost: '$60M', roi: '20×', status: 'in progress', engagement: 'gate' },
      { name: 'Privileged-access rollout (markets)', owner: 'CISO', cost: '$32M', roi: '16×', status: 'in progress', engagement: 'gate' },
      { name: 'DORA operational-resilience program', owner: 'CRO', cost: '$40M', roi: '9×', status: 'in progress', engagement: 'design' },
      { name: 'Quantum-safe crypto pilot', owner: 'CISO', cost: '$15M', roi: '6×', status: 'planned', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'AI fraud & underwriting models', type: 'AI product or feature', valueUsd: 4 * B, horizon: 'This year' },
      { name: 'Core-banking cloud migration', type: 'Cloud platform or migration', valueUsd: 3 * B, horizon: 'Next 12–24 months' },
      { name: 'UK/EU digital-bank expansion', type: 'Market / geographic expansion', valueUsd: 2 * B, horizon: 'Next 12–24 months' },
    ],
    frameworks: ['NIST CSF 2.0', 'PCI DSS', 'SOC 2', 'DORA', 'GLBA', 'SEC Cyber Disclosure'],
    docMaturity: 4,
  },

  // ═══════════════════════════ 4 · RETAIL ═══════════════════════════
  {
    key: 'walmart',
    org_name: 'Walmart Inc.',
    industry: 'Retail / e-commerce',    // → retail
    regions: ['US'],
    currency: 'USD',
    story: 'World\'s largest retailer. Crown jewels are the payment/POS estate, e-commerce platform, and supply-chain systems. PCI DSS, peak-season availability, and vendor/supply-chain risk dominate.',
    financials: { revenue: 681 * B, operatingIncome: 29 * B, netIncome: 20.2 * B, enterpriseValue: 780 * B, sharesOutstanding: 8.03 * B },
    appetite: 300 * M, budget: 600 * M, dataRecords: 255 * M,
    principalRisks: { creditMarket: 25 * B, operational: 22 * B, thirdParty: 12 * B, compliance: 6 * B },
    insurance: { limit: 150 * M, premium: 9 * M, retention: 20 * M, renewal: '2026-08-15' },
    governance: { committee: 'Technology Committee', cadence: 'Quarterly', cisoReportsTo: 'CIO', boardExpertise: 'Yes', ermIntegrated: 'Partially',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-01-30', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 35, decisioning: 'Yes', framework: 'NIST AI RMF', policy: 'Drafted', euAiAct: 'Not in scope', inventory: 'Partially' },
    growth: { pipelineUsd: 6 * B, reviewBeforeWks: '5', reviewNowWks: '3', dealsGated: '10', trustReviews: '18', certs: ['PCI DSS', 'SOC 2 Type II'] },
    seatNames: { ceo: 'D. McMillin', cfo: 'J. Rainy', ciso: 'J. Evanko', cio: 'S. Whiteside', clo: 'R. Eggleston', cro: 'M. Furner' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'knowbe4', 'wiz', 'sap', 'rubrik', 'servicenow', 'securityscorecard', 'salesforce'],
    processes: [
      { name: 'Store checkout & payments (POS)', revenue: '$380B', rto: '2', data: 'PCI, Financial', criticality: 'Critical', tx: '250000000', tolerance: '$15M' },
      { name: 'E-commerce & fulfillment', revenue: '$120B', rto: '4', data: 'PCI, PII', criticality: 'Critical', tx: '40000000', tolerance: '$10M' },
      { name: 'Supply chain & logistics', revenue: '$90B', rto: '6', data: 'Confidential', criticality: 'Critical', tx: '20000000', tolerance: '$8M' },
      { name: 'Merchandising & pricing', revenue: '$50B', rto: '12', data: 'Confidential', criticality: 'High', tx: '5000000', tolerance: '$3M' },
      { name: 'Membership & loyalty (Walmart+)', revenue: '$8B', rto: '12', data: 'PII, PCI', criticality: 'High', tx: '10000000', tolerance: '$2M' },
    ],
    apps: [
      { name: 'POS payment estate', host: 'internet-facing', data: 'PCI, Financial', vendor: 'In-house', eol: 'no', recovery: '4', tx: '250000000', value: '$150M', processes: ['Store checkout & payments (POS)'] },
      { name: 'E-commerce platform', host: 'internet-facing web', data: 'PCI, PII', vendor: 'In-house / Azure', eol: 'no', recovery: '4', tx: '40000000', value: '$110M', processes: ['E-commerce & fulfillment', 'Membership & loyalty (Walmart+)'] },
      { name: 'Order-management system', host: 'application cloud', data: 'PII, PCI', vendor: 'Azure', eol: 'no', recovery: '6', tx: '40000000', value: '$40M', processes: ['E-commerce & fulfillment'] },
      { name: 'Supply-chain control tower', host: 'application on-prem', data: 'Confidential', vendor: 'SAP', eol: 'no', recovery: '8', tx: '20000000', value: '$60M', processes: ['Supply chain & logistics'] },
      { name: 'Customer data platform', host: 'database on-prem', data: 'PII, PCI', vendor: 'Snowflake', eol: 'no', recovery: '12', tx: '5000000', value: '$25M', processes: ['Membership & loyalty (Walmart+)'] },
      { name: 'Legacy pricing mainframe', host: 'application on-prem', data: 'Confidential', vendor: 'IBM', eol: 'yes', recovery: '24', tx: '5000000', value: '$18M', processes: ['Merchandising & pricing'] },
    ],
    risks: [
      { title: 'POS malware / cardholder-data theft', severity: 'Critical', asset: 'POS payment estate', exposure: '$150M', status: 'open' },
      { title: 'E-commerce peak-season outage', severity: 'Critical', asset: 'E-commerce platform', exposure: '$90M', status: 'open' },
      { title: 'Supply-chain ransomware', severity: 'High', asset: 'Supply-chain control tower', exposure: '$55M', status: 'open' },
      { title: 'Customer-data breach (loyalty)', severity: 'High', asset: 'Customer data platform', exposure: '$28M', status: 'open' },
      { title: 'Legacy mainframe end-of-life exploit', severity: 'High', asset: 'Legacy pricing mainframe', exposure: '$18M', status: 'open' },
    ],
    initiatives: [
      { name: 'POS tokenization & segmentation', owner: 'CISO', cost: '$22M', roi: '17×', status: 'in progress', engagement: 'gate' },
      { name: 'Peak-season resilience program', owner: 'CIO', cost: '$16M', roi: '12×', status: 'in progress', engagement: 'design' },
      { name: 'Third-party / supplier risk uplift', owner: 'CRO', cost: '$8M', roi: '9×', status: 'planned', engagement: 'design' },
      { name: 'Mainframe decommission', owner: 'CIO', cost: '$11M', roi: '7×', status: 'planned', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'AI-driven personalization & search', type: 'AI product or feature', valueUsd: 2 * B, horizon: 'This year' },
      { name: 'Marketplace / advertising expansion', type: 'New digital product', valueUsd: 3 * B, horizon: 'Next 12–24 months' },
      { name: 'Warehouse automation rollout', type: 'Data / analytics initiative', valueUsd: 1.5 * B, horizon: 'This year' },
    ],
    frameworks: ['PCI DSS', 'NIST CSF 2.0', 'SOC 2', 'CCPA'],
    docMaturity: 3,
  },

  // ═══════════════════════════ 5 · GOVERNMENT ═══════════════════════════
  {
    key: 'state-california',
    org_name: 'State of California',
    industry: 'Government / Public sector',  // → gov
    regions: ['US'],
    currency: 'USD',
    story: 'Largest U.S. state government (~39.5M residents, ~$414B total budget). Crown jewels are resident PII/benefits systems, tax records, and critical public services. No net income / EPS — a good null-handling test. State breach-notification law and public-service continuity dominate.',
    financials: { revenue: 413.8 * B, operatingIncome: null, netIncome: null, enterpriseValue: null, sharesOutstanding: null },
    appetite: 200 * M, budget: 250 * M, dataRecords: 39.5 * M,
    principalRisks: { creditMarket: null, operational: 12 * B, thirdParty: 4 * B, compliance: 3 * B },
    insurance: { limit: 50 * M, premium: 4 * M, retention: 10 * M, renewal: '2026-07-01' },
    governance: { committee: 'Technology Committee', cadence: 'Semi-annually', cisoReportsTo: 'CIO', boardExpertise: 'No', ermIntegrated: 'Partially',
      ir: { tested: 'Yes — older than 12 months', lastTabletop: '2024-11-01', retainer: 'No', ransomwarePolicy: 'Informal' } },
    aiGovernance: { systems: 15, decisioning: 'Piloting', framework: 'NIST AI RMF', policy: 'Drafted', euAiAct: 'Not in scope', inventory: 'Partially' },
    growth: null,
    seatNames: { ceo: 'Governor / Cabinet', cfo: 'State Controller', ciso: 'State CISO', cio: 'State CIO (CDT)', clo: 'Attorney General', cro: 'Chief Risk (DGS)' },
    tools: ['okta', 'defender', 'splunk', 'qualys', 'knowbe4', 'servicenow', 'rubrik', 'onetrust', 'servicenow_grc', 'cisa'],
    processes: [
      { name: 'Health & human services benefits', revenue: '$150B', rto: '6', data: 'PII, PHI', criticality: 'Critical', tx: '8000000', tolerance: '$4M' },
      { name: 'Tax collection & revenue (FTB)', revenue: '$120B', rto: '8', data: 'PII, Financial', criticality: 'Critical', tx: '3000000', tolerance: '$5M' },
      { name: 'Unemployment & disability (EDD)', revenue: '$40B', rto: '6', data: 'PII, Financial', criticality: 'Critical', tx: '5000000', tolerance: '$3M' },
      { name: 'Motor vehicles & licensing (DMV)', revenue: '$8B', rto: '12', data: 'PII', criticality: 'High', tx: '2000000', tolerance: '$1M' },
      { name: 'Emergency services & public safety', revenue: '$5B', rto: '2', data: 'PII, Confidential', criticality: 'Critical', tx: '1000000', tolerance: '$2M' },
    ],
    apps: [
      { name: 'Benefits eligibility system (CalSAWS)', host: 'internet-facing web', data: 'PII, PHI', vendor: 'Accenture', eol: 'no', recovery: '12', tx: '8000000', value: '$30M', processes: ['Health & human services benefits'] },
      { name: 'Tax filing & records (FTB)', host: 'internet-facing', data: 'PII, Financial', vendor: 'In-house', eol: 'no', recovery: '12', tx: '3000000', value: '$40M', processes: ['Tax collection & revenue (FTB)'] },
      { name: 'Unemployment claims platform (EDD)', host: 'internet-facing web', data: 'PII, Financial', vendor: 'Deloitte', eol: 'no', recovery: '8', tx: '5000000', value: '$25M', processes: ['Unemployment & disability (EDD)'] },
      { name: 'DMV records system', host: 'application on-prem', data: 'PII', vendor: 'In-house', eol: 'yes', recovery: '24', tx: '2000000', value: '$12M', processes: ['Motor vehicles & licensing (DMV)'] },
      { name: 'Statewide 911 / dispatch', host: 'application on-prem', data: 'PII, Confidential', vendor: 'Motorola', eol: 'no', recovery: '2', tx: '1000000', value: '$20M', processes: ['Emergency services & public safety'] },
      { name: 'Legacy COBOL benefits mainframe', host: 'application on-prem', data: 'PII, Financial', vendor: 'IBM', eol: 'yes', recovery: '48', tx: '4000000', value: '$15M', processes: ['Unemployment & disability (EDD)'] },
    ],
    risks: [
      { title: 'Resident PII breach (benefits)', severity: 'Critical', asset: 'Benefits eligibility system (CalSAWS)', exposure: '$60M', status: 'open' },
      { title: 'Tax-records exfiltration', severity: 'Critical', asset: 'Tax filing & records (FTB)', exposure: '$70M', status: 'open' },
      { title: 'Unemployment-fraud / claims takeover', severity: 'Critical', asset: 'Unemployment claims platform (EDD)', exposure: '$45M', status: 'open' },
      { title: 'Legacy mainframe ransomware', severity: 'High', asset: 'Legacy COBOL benefits mainframe', exposure: '$25M', status: 'open' },
      { title: '911 / dispatch service disruption', severity: 'Critical', asset: 'Statewide 911 / dispatch', exposure: '$30M', status: 'open' },
    ],
    initiatives: [
      { name: 'Statewide MFA & identity modernization', owner: 'CISO', cost: '$18M', roi: '13×', status: 'in progress', engagement: 'design' },
      { name: 'Legacy mainframe migration', owner: 'CIO', cost: '$22M', roi: '8×', status: 'planned', engagement: 'design' },
      { name: 'Cal-CSIC threat-monitoring uplift', owner: 'CISO', cost: '$9M', roi: '10×', status: 'in progress', engagement: 'gate' },
      { name: 'IR retainer & tabletop program', owner: 'CISO', cost: '$4M', roi: '12×', status: 'planned', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'GenAI resident-services pilots', type: 'AI product or feature', valueUsd: 500 * M, horizon: 'This year' },
      { name: 'Benefits-systems cloud migration', type: 'Cloud platform or migration', valueUsd: 1.2 * B, horizon: 'Next 12–24 months' },
      { name: 'Digital-identity (mDL) program', type: 'New digital product', valueUsd: 300 * M, horizon: 'Next 12–24 months' },
    ],
    frameworks: ['NIST CSF 2.0', 'NIST 800-53', 'FedRAMP', 'CCPA', 'State breach-notification law'],
    docMaturity: 2,
  },

  // ═══════════════════════════ 6 · MANUFACTURING ═══════════════════════════
  {
    key: 'boeing',
    org_name: 'The Boeing Company',
    industry: 'Manufacturing',          // → mfg
    regions: ['US'],
    currency: 'USD',
    story: 'Aerospace & defense manufacturer (FY2024 was a $11.8B net-loss year — a good negative-earnings test). Crown jewels are design IP, the OT/factory floor, and defense programs. ITAR/CMMC, OT safety, and IP theft dominate.',
    financials: { revenue: 66.5 * B, operatingIncome: -10.7 * B, netIncome: -11.8 * B, enterpriseValue: 130 * B, sharesOutstanding: 750 * M },
    appetite: 250 * M, budget: 400 * M, dataRecords: 12 * M,
    principalRisks: { creditMarket: 55 * B, operational: 30 * B, thirdParty: 15 * B, compliance: 8 * B },
    insurance: { limit: 150 * M, premium: 10 * M, retention: 25 * M, renewal: '2026-11-01' },
    governance: { committee: 'Audit Committee', cadence: 'Quarterly', cisoReportsTo: 'CIO', boardExpertise: 'Yes', ermIntegrated: 'Yes',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-05-05', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 10, decisioning: 'Piloting', framework: 'NIST AI RMF', policy: 'Drafted', euAiAct: 'Not in scope', inventory: 'Partially' },
    growth: { pipelineUsd: 435 * B, reviewBeforeWks: '8', reviewNowWks: '4', dealsGated: '6', trustReviews: '12', certs: ['CMMC L2', 'AS9100', 'ISO 27001'] },
    seatNames: { ceo: 'K. Ortsberg', cfo: 'B. Westbrook', ciso: 'R. Delrio', cio: 'S. Chandra', clo: 'B. Karsten', cro: 'U. Lindqvist' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'knowbe4', 'wiz', 'sap', 'rubrik', 'servicenow', 'recordedfuture', 'securityscorecard'],
    processes: [
      { name: 'Commercial airplane production', revenue: '$22B', rto: '8', data: 'IP, Confidential', criticality: 'Critical', tx: '50000', tolerance: '$12M' },
      { name: 'Defense, space & security programs', revenue: '$24B', rto: '6', data: 'IP, ITAR, Classified', criticality: 'Critical', tx: '30000', tolerance: '$15M' },
      { name: 'Global services & MRO', revenue: '$20B', rto: '12', data: 'Confidential, PII', criticality: 'High', tx: '200000', tolerance: '$4M' },
      { name: 'Engineering & design', revenue: '$0', rto: '8', data: 'IP, Design Data', criticality: 'Critical', tx: '100000', tolerance: '$10M' },
      { name: 'Supply chain & procurement', revenue: '$40B', rto: '12', data: 'Confidential', criticality: 'High', tx: '500000', tolerance: '$3M' },
    ],
    apps: [
      { name: 'PLM / design-data vault (CATIA/Teamcenter)', host: 'application on-prem', data: 'IP, CUI, Design Data', vendor: 'Siemens', eol: 'no', recovery: '8', tx: '100000', value: '$90M', processes: ['Engineering & design', 'Commercial airplane production'] },
      { name: 'Defense-program enclave', host: 'application on-prem', data: 'Classified, CUI, ITAR', vendor: 'In-house', eol: 'no', recovery: '6', tx: '30000', value: '$120M', processes: ['Defense, space & security programs', 'Engineering & design'] },
      { name: 'Factory OT / MES', host: 'application on-prem', data: 'CUI, Confidential, OT', vendor: 'Rockwell', eol: 'yes', recovery: '12', tx: '80000', value: '$70M', processes: ['Commercial airplane production'] },
      { name: 'ERP (SAP)', host: 'application on-prem', data: 'Financial, Confidential', vendor: 'SAP', eol: 'no', recovery: '12', tx: '500000', value: '$40M', processes: ['Supply chain & procurement'] },
      { name: 'Supplier collaboration portal', host: 'internet-facing web', data: 'Confidential', vendor: 'In-house', eol: 'no', recovery: '12', tx: '200000', value: '$14M', processes: ['Supply chain & procurement', 'Global services & MRO'] },
      { name: 'Fleet-services data platform', host: 'application cloud', data: 'Confidential, PII', vendor: 'AWS', eol: 'no', recovery: '12', tx: '200000', value: '$18M', processes: ['Global services & MRO'] },
    ],
    risks: [
      { title: 'Design-IP theft (nation-state)', severity: 'Critical', asset: 'PLM / design-data vault (CATIA/Teamcenter)', exposure: '$140M', status: 'open' },
      { title: 'Defense-program / ITAR data breach', severity: 'Critical', asset: 'Defense-program enclave', exposure: '$160M', status: 'open' },
      { title: 'OT ransomware halting production', severity: 'Critical', asset: 'Factory OT / MES', exposure: '$95M', status: 'open' },
      { title: 'Supplier-portal compromise', severity: 'High', asset: 'Supplier collaboration portal', exposure: '$30M', status: 'open' },
      { title: 'ERP financial-data exposure', severity: 'High', asset: 'ERP (SAP)', exposure: '$25M', status: 'open' },
    ],
    initiatives: [
      { name: 'OT/IT segmentation (factory)', owner: 'CISO', cost: '$34M', roi: '16×', status: 'in progress', engagement: 'gate' },
      { name: 'CMMC L2 remediation program', owner: 'CISO', cost: '$26M', roi: '10×', status: 'in progress', engagement: 'design' },
      { name: 'Design-vault DLP & isolation', owner: 'CISO', cost: '$19M', roi: '14×', status: 'in progress', engagement: 'gate' },
      { name: 'Factory-OT patch & EOL retirement', owner: 'CIO', cost: '$15M', roi: '9×', status: 'planned', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'Digital-twin manufacturing', type: 'Data / analytics initiative', valueUsd: 2 * B, horizon: 'Next 12–24 months' },
      { name: '777X production ramp', type: 'New digital product', valueUsd: 4 * B, horizon: 'This year' },
      { name: 'Defense-cloud (IL5) migration', type: 'Cloud platform or migration', valueUsd: 1 * B, horizon: 'Next 12–24 months' },
    ],
    frameworks: ['CMMC 2.0', 'NIST 800-171', 'ITAR', 'AS9100', 'NIST CSF 2.0'],
    docMaturity: 3,
  },

  // ═══════════════════════════ 7 · ENERGY ═══════════════════════════
  {
    key: 'duke-energy',
    org_name: 'Duke Energy Corporation',
    industry: 'Energy / Utilities',     // → energy
    regions: ['US'],
    currency: 'USD',
    story: 'Regulated electric & gas utility (~8.4M customers). Crown jewels are the grid control systems (SCADA/EMS/DERMS), the OT estate, and customer/billing data. NERC CIP, OT/ICS safety, and grid continuity dominate.',
    financials: { revenue: 30.36 * B, operatingIncome: 8.2 * B, netIncome: 4.61 * B, enterpriseValue: 90 * B, sharesOutstanding: 775 * M },
    appetite: 200 * M, budget: 300 * M, dataRecords: 8.4 * M,
    principalRisks: { creditMarket: 70 * B, operational: 18 * B, thirdParty: 6 * B, compliance: 5 * B },
    insurance: { limit: 120 * M, premium: 8 * M, retention: 20 * M, renewal: '2026-09-15' },
    governance: { committee: 'Dedicated Cybersecurity Committee', cadence: 'Quarterly', cisoReportsTo: 'CEO', boardExpertise: 'Yes', ermIntegrated: 'Yes',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-03-01', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 8, decisioning: 'Piloting', framework: 'NIST AI RMF', policy: 'Drafted', euAiAct: 'Not in scope', inventory: 'Partially' },
    growth: { pipelineUsd: 3 * B, reviewBeforeWks: '6', reviewNowWks: '3', dealsGated: '5', trustReviews: '9', certs: ['NERC CIP', 'ISO 27001', 'SOC 2 Type II'] },
    seatNames: { ceo: 'L. Mauldin', cfo: 'B. Savoy', ciso: 'M. Reichert', cio: 'B. Savage', clo: 'K. Trent', cro: 'J. Brooks' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'knowbe4', 'wiz', 'rubrik', 'servicenow', 'recordedfuture', 'cisa', 'securityscorecard'],
    processes: [
      { name: 'Electric grid operations (T&D)', revenue: '$20B', rto: '1', data: 'OT, Confidential', criticality: 'Critical', tx: '1000000', tolerance: '$20M' },
      { name: 'Power generation (nuclear/gas/renew)', revenue: '$8B', rto: '2', data: 'OT, Confidential', criticality: 'Critical', tx: '200000', tolerance: '$12M' },
      { name: 'Customer billing & metering (AMI)', revenue: '$2B', rto: '8', data: 'PII, Financial', criticality: 'High', tx: '8400000', tolerance: '$3M' },
      { name: 'Gas distribution', revenue: '$3B', rto: '2', data: 'OT, Confidential', criticality: 'Critical', tx: '500000', tolerance: '$8M' },
      { name: 'Grid modernization & DER', revenue: '$1B', rto: '8', data: 'OT, Confidential', criticality: 'High', tx: '100000', tolerance: '$2M' },
    ],
    apps: [
      { name: 'SCADA / EMS grid control', host: 'application on-prem', data: 'OT, CUI, Critical Infrastructure', vendor: 'GE / OSIsoft', eol: 'no', recovery: '2', tx: '1000000', value: '$140M', processes: ['Electric grid operations (T&D)', 'Power generation (nuclear/gas/renew)', 'Grid modernization & DER'] },
      { name: 'Generation plant DCS/OT', host: 'application on-prem', data: 'OT, CUI, Confidential', vendor: 'Emerson', eol: 'no', recovery: '2', tx: '200000', value: '$90M', processes: ['Power generation (nuclear/gas/renew)'] },
      { name: 'DERMS / grid-edge platform', host: 'application cloud', data: 'OT, Confidential', vendor: 'Schneider', eol: 'no', recovery: '4', tx: '100000', value: '$30M', processes: ['Grid modernization & DER'] },
      { name: 'AMI meter head-end', host: 'internet-facing', data: 'PII, OT', vendor: 'Itron', eol: 'no', recovery: '8', tx: '8400000', value: '$25M', processes: ['Customer billing & metering (AMI)'] },
      { name: 'Customer billing (CIS)', host: 'application cloud', data: 'PII, Financial', vendor: 'SAP', eol: 'no', recovery: '8', tx: '8400000', value: '$18M', processes: ['Customer billing & metering (AMI)'] },
      { name: 'Gas SCADA', host: 'application on-prem', data: 'OT, CUI, Critical Infrastructure', vendor: 'Honeywell', eol: 'yes', recovery: '2', tx: '500000', value: '$60M', processes: ['Gas distribution', 'Electric grid operations (T&D)'] },
    ],
    risks: [
      { title: 'Grid-control (SCADA) compromise / blackout', severity: 'Critical', asset: 'SCADA / EMS grid control', exposure: '$200M', status: 'open' },
      { title: 'Generation-plant OT sabotage', severity: 'Critical', asset: 'Generation plant DCS/OT', exposure: '$110M', status: 'open' },
      { title: 'Gas-SCADA safety incident', severity: 'Critical', asset: 'Gas SCADA', exposure: '$90M', status: 'open' },
      { title: 'AMI / customer-data breach', severity: 'High', asset: 'AMI meter head-end', exposure: '$25M', status: 'open' },
      { title: 'Billing-system fraud / outage', severity: 'High', asset: 'Customer billing (CIS)', exposure: '$18M', status: 'open' },
    ],
    initiatives: [
      { name: 'OT network segmentation (NERC CIP)', owner: 'CISO', cost: '$30M', roi: '18×', status: 'in progress', engagement: 'gate' },
      { name: 'SCADA anomaly-detection (Dragos)', owner: 'CISO', cost: '$14M', roi: '15×', status: 'in progress', engagement: 'gate' },
      { name: 'Gas-SCADA EOL replacement', owner: 'CIO', cost: '$20M', roi: '9×', status: 'planned', engagement: 'design' },
      { name: 'Grid-resilience & black-start program', owner: 'COO', cost: '$18M', roi: '11×', status: 'in progress', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'AI grid-optimization & forecasting', type: 'AI product or feature', valueUsd: 800 * M, horizon: 'Next 12–24 months' },
      { name: 'Grid modernization (DER/EV)', type: 'Data / analytics initiative', valueUsd: 4 * B, horizon: 'Next 12–24 months' },
      { name: 'Customer-platform cloud migration', type: 'Cloud platform or migration', valueUsd: 600 * M, horizon: 'This year' },
    ],
    frameworks: ['NERC CIP', 'NIST CSF 2.0', 'IEC 62443', 'SOC 2', 'TSA Pipeline Security'],
    docMaturity: 4,
  },

  // ═══════════════════════════ 8 · TELECOMMUNICATIONS ═══════════════════════════
  {
    key: 'att',
    org_name: 'AT&T Inc.',
    industry: 'Telecommunications',     // → telecom lens
    regions: ['US'],
    currency: 'USD',
    story: 'Largest U.S. wireless & fiber carrier (~118M wireless subscribers). Crown jewels are the mobile/network core, subscriber CPNI, and lawful-intercept infrastructure — the 2024 Salt Typhoon telecom intrusions and CPNI/call-records breaches are the defining sector scenarios.',
    financials: { revenue: 122.3 * B, operatingIncome: 23 * B, netIncome: 10.7 * B, enterpriseValue: 160 * B, sharesOutstanding: 7.18 * B },
    appetite: 300 * M, budget: 500 * M, dataRecords: 110 * M,
    principalRisks: { creditMarket: 130 * B, operational: 25 * B, thirdParty: 8 * B, compliance: 6 * B },
    insurance: { limit: 150 * M, premium: 9 * M, retention: 25 * M, renewal: '2026-10-15' },
    governance: { committee: 'Audit Committee', cadence: 'Quarterly', cisoReportsTo: 'CIO', boardExpertise: 'Yes', ermIntegrated: 'Yes',
      ir: { tested: 'Yes — tabletop within 12 months', lastTabletop: '2026-02-20', retainer: 'Yes', ransomwarePolicy: 'Board-approved policy' } },
    aiGovernance: { systems: 25, decisioning: 'Piloting', framework: 'NIST AI RMF', policy: 'Drafted', euAiAct: 'Not in scope', inventory: 'Partially' },
    growth: { pipelineUsd: 5 * B, reviewBeforeWks: '5', reviewNowWks: '3', dealsGated: '8', trustReviews: '12', certs: ['SOC 2 Type II', 'ISO 27001', 'NIST CSF 2.0'] },
    seatNames: { ceo: 'J. Stanwick', cfo: 'P. Deschenes', ciso: 'R. Boyer', cio: 'J. McElfresh', clo: 'D. McAtee II', cro: 'S. Krishnan' },
    tools: ['okta', 'defender', 'splunk', 'cyberark', 'qualys', 'knowbe4', 'wiz', 'rubrik', 'servicenow', 'recordedfuture', 'onetrust', 'securityscorecard'],
    processes: [
      { name: 'Mobile network operations (5G/wireless)', revenue: '$80B', rto: '1', data: 'PII, CPNI, OT', criticality: 'Critical', tx: '500000000', tolerance: '$18M' },
      { name: 'Broadband & fiber (consumer/business)', revenue: '$30B', rto: '2', data: 'PII, CPNI', criticality: 'Critical', tx: '100000000', tolerance: '$8M' },
      { name: 'Business & enterprise connectivity', revenue: '$30B', rto: '2', data: 'PII, Confidential', criticality: 'Critical', tx: '20000000', tolerance: '$6M' },
      { name: 'Billing & customer care', revenue: '$10B', rto: '6', data: 'PII, PCI, Financial', criticality: 'High', tx: '120000000', tolerance: '$4M' },
      { name: 'Interconnection & signaling (SS7/roaming)', revenue: '$5B', rto: '1', data: 'CPNI, OT', criticality: 'Critical', tx: '50000000', tolerance: '$5M' },
    ],
    apps: [
      { name: '5G wireless core (EPC/5GC)', host: 'application on-prem', data: 'PII, CPNI, OT', vendor: 'Ericsson', eol: 'no', recovery: '2', tx: '500000000', value: '$180M', processes: ['Mobile network operations (5G/wireless)', 'Interconnection & signaling (SS7/roaming)', 'Business & enterprise connectivity'] },
      { name: 'Lawful-intercept & provisioning', host: 'application on-prem', data: 'CPNI, CUI, Confidential', vendor: 'In-house', eol: 'no', recovery: '4', tx: '1000000', value: '$120M', processes: ['Interconnection & signaling (SS7/roaming)', 'Mobile network operations (5G/wireless)'] },
      { name: 'SS7 / Diameter signaling gateway', host: 'internet-facing', data: 'PII, CPNI, OT', vendor: 'Oracle Communications', eol: 'yes', recovery: '2', tx: '50000000', value: '$60M', processes: ['Interconnection & signaling (SS7/roaming)', 'Mobile network operations (5G/wireless)'] },
      { name: 'Customer data platform (CRM)', host: 'database on-prem', data: 'PII, CPNI, Financial', vendor: 'Oracle', eol: 'no', recovery: '8', tx: '120000000', value: '$70M', processes: ['Billing & customer care', 'Mobile network operations (5G/wireless)'] },
      { name: 'Broadband & fiber access network', host: 'internet-facing', data: 'PII, CPNI', vendor: 'Nokia', eol: 'no', recovery: '4', tx: '100000000', value: '$70M', processes: ['Broadband & fiber (consumer/business)'] },
      { name: 'Billing / OSS-BSS', host: 'application cloud', data: 'PII, PCI, Financial', vendor: 'Amdocs', eol: 'no', recovery: '6', tx: '120000000', value: '$40M', processes: ['Billing & customer care'] },
    ],
    risks: [
      { title: 'Nation-state intrusion into signaling / call records', severity: 'Critical', asset: 'SS7 / Diameter signaling gateway', exposure: '$180M', status: 'open' },
      { title: 'Lawful-intercept system compromise', severity: 'Critical', asset: 'Lawful-intercept & provisioning', exposure: '$150M', status: 'open' },
      { title: 'Subscriber CPNI / call-records breach', severity: 'Critical', asset: 'Customer data platform (CRM)', exposure: '$120M', status: 'open' },
      { title: '5G core disruption / mass outage', severity: 'Critical', asset: '5G wireless core (EPC/5GC)', exposure: '$110M', status: 'open' },
      { title: 'Broadband access DDoS / outage', severity: 'High', asset: 'Broadband & fiber access network', exposure: '$40M', status: 'open' },
    ],
    initiatives: [
      { name: 'Network segmentation & signaling hardening', owner: 'CISO', cost: '$30M', roi: '17×', status: 'in progress', engagement: 'gate' },
      { name: 'Lawful-intercept isolation & monitoring', owner: 'CISO', cost: '$12M', roi: '15×', status: 'in progress', engagement: 'gate' },
      { name: 'CPNI data-protection & DLP', owner: 'CISO', cost: '$16M', roi: '13×', status: 'in progress', engagement: 'design' },
      { name: 'Legacy SS7 retirement / Diameter migration', owner: 'CIO', cost: '$18M', roi: '8×', status: 'planned', engagement: 'design' },
    ],
    strategicInitiatives: [
      { name: 'AI network-ops & customer care', type: 'AI product or feature', valueUsd: 1.5 * B, horizon: 'This year' },
      { name: 'Fiber expansion to 60M locations', type: 'Market / geographic expansion', valueUsd: 4 * B, horizon: 'Next 12–24 months' },
      { name: '5G standalone core rollout', type: 'Cloud platform or migration', valueUsd: 2 * B, horizon: 'Next 12–24 months' },
    ],
    frameworks: ['NIST CSF 2.0', 'FCC CPNI Rules', 'CISA Cross-Sector', 'SOC 2', 'ISO 27001'],
    docMaturity: 3,
  },
];
