'use strict';

const crypto = require('crypto');
const Alert = require('../models/Alert');
const Vendor = require('../models/Vendor');
const VendorRiskSignal = require('../models/VendorRiskSignal');
const { getQueue, addJob } = require('../workers/queue');
const logger = require('../utils/logger');

// Generate UUID v4
const uuidv4 = () => crypto.randomUUID();

// Job type for alerts
const ALERT_JOB_TYPE = 'SEND_ALERT';

/**
 * Alert Service
 *
 * Manages vendor monitoring alerts with rule evaluation, email delivery,
 * and Slack integration. Supports multiple alert channels and async delivery.
 */
class AlertService {
  constructor() {
    // SendGrid configuration
    this.sendgridApiKey = process.env.SENDGRID_API_KEY;
    if (this.sendgridApiKey) {
      this.sendgrid = require('@sendgrid/mail');
      this.sendgrid.setApiKey(this.sendgridApiKey);
    }

    // Slack webhook URLs by severity
    this.slackWebhooks = {
      critical: process.env.SLACK_WEBHOOK_CRITICAL,
      high: process.env.SLACK_WEBHOOK_WARNING,
      medium: process.env.SLACK_WEBHOOK_WARNING,
      low: process.env.SLACK_WEBHOOK_INFO,
      info: process.env.SLACK_WEBHOOK_INFO
    };

    // Frontend URL for links
    this.frontendUrl = process.env.FRONTEND_URL || 'http://localhost:5173';
  }

  /**
   * Send an alert
   * @param {Object} params - Alert parameters
   * @param {string} params.organizationId - Organization ID
   * @param {string} params.vendorId - Vendor ID
   * @param {string} params.type - Alert type
   * @param {string} params.severity - Alert severity
   * @param {string} params.message - Alert message
   * @param {Object} [params.data] - Alert data payload
   * @returns {Promise<Object>} Created alert
   */
  async sendAlert({ organizationId, vendorId, type, severity, message, data }) {
    try {
      // Get vendor information
      const vendor = await Vendor.findById(vendorId);
      if (!vendor) {
        throw new Error(`Vendor not found: ${vendorId}`);
      }

      // Create alert object (id will be generated by model)
      const alert = {
        organizationId,
        vendorId,
        vendorName: vendor.name,
        type,
        severity,
        message,
        data: {
          ...data,
          vendorId
        },
        createdAt: new Date()
      };

      // Save to database
      await Alert.create(alert);

      // Queue for async delivery
      await addJob(ALERT_JOB_TYPE, alert, {
        priority: this.getPriority(severity),
        attempts: 3,
        backoff: { type: 'exponential', delay: 1000 }
      });

      logger.info('Alert queued for delivery', {
        alertId: alert.id,
        type,
        severity,
        vendor: vendor.name
      });

      return alert;
    } catch (error) {
      logger.error('Failed to send alert', {
        error: error.message,
        organizationId,
        vendorId,
        type
      });
      throw error;
    }
  }

  /**
   * Evaluate alert rules for a vendor
   * @param {string} vendorId - Vendor ID
   * @param {string} organizationId - Organization ID
   * @returns {Promise<Object[]>} Array of triggered alerts
   */
  async evaluateRules(vendorId, organizationId) {
    try {
      const vendor = await Vendor.findById(vendorId);
      if (!vendor) {
        throw new Error(`Vendor not found: ${vendorId}`);
      }

      // Get vendor signals
      const signals = await VendorRiskSignal.findActiveByVendor(vendorId, organizationId);
      const triggeredAlerts = [];

      // Rule 1: Critical signal detected
      const criticalSignals = signals.filter(s => s.severity === 'Critical');
      if (criticalSignals.length > 0) {
        const alert = await this.sendAlert({
          organizationId,
          vendorId,
          type: 'critical_signal',
          severity: 'Critical',
          message: `Critical security signals detected for ${vendor.name}`,
          data: {
            signals: criticalSignals.map(s => ({
              sourceName: s.sourceName,
              severity: s.severity,
              description: s.description,
              observedAt: s.observedAt,
              category: s.signalCategory
            }))
          }
        });
        triggeredAlerts.push(alert);
      }

      // Rule 2: Risk score increased by >20
      const previousScore = vendor.previousRiskScore || 0;
      const currentScore = vendor.securityScore || 0;
      const scoreChange = currentScore - previousScore;

      if (scoreChange > 20 && previousScore > 0) {
        const alert = await this.sendAlert({
          organizationId,
          vendorId,
          type: 'score_increase',
          severity: 'High',
          message: `Risk score increased by ${scoreChange} points for ${vendor.name}`,
          data: {
            previous: previousScore,
            current: currentScore,
            change: scoreChange,
            previousGrade: this.getGradeFromScore(previousScore),
            currentGrade: this.getGradeFromScore(currentScore)
          }
        });
        triggeredAlerts.push(alert);
      }

      // Rule 3: Grade degradation
      const previousGrade = this.getGradeFromScore(previousScore);
      const currentGrade = this.getGradeFromScore(currentScore);

      if (this.isGradeWorse(currentGrade, previousGrade) && previousScore > 0) {
        const alert = await this.sendAlert({
          organizationId,
          vendorId,
          type: 'grade_degradation',
          severity: 'Medium',
          message: `Security grade degraded from ${previousGrade} to ${currentGrade} for ${vendor.name}`,
          data: {
            from: previousGrade,
            to: currentGrade,
            previousScore,
            currentScore
          }
        });
        triggeredAlerts.push(alert);
      }

      // Rule 4: Multi-provider confirmation
      const confirmedIssues = this.findConfirmedIssues(signals);
      if (confirmedIssues.length > 0) {
        const alert = await this.sendAlert({
          organizationId,
          vendorId,
          type: 'multi_provider_confirmed',
          severity: 'High',
          message: `Multiple providers confirmed ${confirmedIssues.length} issue(s) for ${vendor.name}`,
          data: {
            issues: confirmedIssues
          }
        });
        triggeredAlerts.push(alert);
      }

      logger.info('Alert rule evaluation complete', {
        vendorId,
        organizationId,
        triggeredCount: triggeredAlerts.length
      });

      return triggeredAlerts;
    } catch (error) {
      logger.error('Failed to evaluate alert rules', {
        error: error.message,
        vendorId,
        organizationId
      });
      throw error;
    }
  }

  /**
   * Send alert via email
   * @param {Object} alert - Alert object
   * @returns {Promise<void>}
   */
  async sendEmail(alert) {
    if (!this.sendgridApiKey || !this.sendgrid) {
      logger.warn('SendGrid not configured, skipping email delivery', {
        alertId: alert.id
      });
      return;
    }

    try {
      const { getEmailTemplate } = require('../utils/emailTemplates');
      const template = getEmailTemplate(alert);
      const recipients = await this.getAlertRecipients(alert.organizationId, alert.type);

      if (recipients.length === 0) {
        logger.warn('No recipients found for alert', {
          alertId: alert.id,
          organizationId: alert.organizationId,
          type: alert.type
        });
        await Alert.updateDeliveryStatus(alert.id, 'sent', {
          channel: 'email',
          note: 'No recipients configured'
        });
        return;
      }

      await this.sendgrid.sendMultiple({
        to: recipients,
        from: process.env.SENDGRID_FROM_EMAIL || 'alerts@cyberrx.com',
        subject: template.subject,
        text: template.text,
        html: template.html
      });

      await Alert.updateDeliveryStatus(alert.id, 'delivered', {
        channel: 'email',
        recipientCount: recipients.length
      });

      logger.info('Email alert sent successfully', {
        alertId: alert.id,
        recipientCount: recipients.length
      });
    } catch (error) {
      logger.error('Failed to send email alert', {
        alertId: alert.id,
        error: error.message
      });
      await Alert.updateDeliveryStatus(alert.id, 'failed', {
        channel: 'email',
        error: error.message
      });
      throw error;
    }
  }

  /**
   * Send alert via Slack webhook
   * @param {Object} alert - Alert object
   * @returns {Promise<void>}
   */
  async sendSlack(alert) {
    const axios = require('axios');
    const webhook = this.slackWebhooks[alert.severity.toLowerCase()];

    if (!webhook) {
      logger.warn('Slack webhook not configured for severity', {
        alertId: alert.id,
        severity: alert.severity
      });
      return;
    }

    try {
      const blocks = this.getSlackBlocks(alert);

      await axios.post(webhook, { blocks });

      await Alert.updateDeliveryStatus(alert.id, 'delivered', {
        channel: 'slack'
      });

      logger.info('Slack alert sent successfully', {
        alertId: alert.id,
        severity: alert.severity
      });
    } catch (error) {
      logger.error('Failed to send Slack alert', {
        alertId: alert.id,
        error: error.message
      });
      await Alert.updateDeliveryStatus(alert.id, 'failed', {
        channel: 'slack',
        error: error.message
      });
      throw error;
    }
  }

  /**
   * Get alert recipients for organization
   * @param {string} organizationId - Organization ID
   * @param {string} alertType - Alert type
   * @returns {Promise<string[]>} Array of email addresses
   */
  async getAlertRecipients(organizationId, alertType) {
    // TODO: Implement organization-specific alert preferences
    // For now, return a default email from environment
    const defaultEmail = process.env.DEFAULT_ALERT_EMAIL || 'admin@cyberrx.com';
    return [defaultEmail];
  }

  /**
   * Find issues confirmed by multiple providers
   * @param {Object[]} signals - Array of signals
   * @returns {Object[]} Array of confirmed issues
   */
  findConfirmedIssues(signals) {
    // Group signals by category
    const signalsByCategory = {};

    signals.forEach(signal => {
      const category = signal.signalCategory;
      if (!signalsByCategory[category]) {
        signalsByCategory[category] = [];
      }
      signalsByCategory[category].push(signal);
    });

    // Find categories with 2+ different sources
    const confirmedIssues = [];

    Object.entries(signalsByCategory).forEach(([category, categorySignals]) => {
      const uniqueSources = new Set(categorySignals.map(s => s.sourceName));

      if (uniqueSources.size >= 2) {
        // Find highest severity
        const severityOrder = ['Critical', 'High', 'Medium', 'Low', 'Info'];
        const highestSeverity = categorySignals.reduce((highest, signal) => {
          return severityOrder.indexOf(signal.severity) < severityOrder.indexOf(highest)
            ? signal.severity
            : highest;
        }, 'Info');

        confirmedIssues.push({
          category,
          providers: Array.from(uniqueSources),
          severity: highestSeverity,
          confidence: 'High',
          signalCount: categorySignals.length
        });
      }
    });

    return confirmedIssues;
  }

  /**
   * Get grade from score
   * @param {number} score - Score (0-100)
   * @returns {string} Grade (A, B, C, D, F)
   */
  getGradeFromScore(score) {
    if (score >= 90) return 'A';
    if (score >= 80) return 'B';
    if (score >= 70) return 'C';
    if (score >= 60) return 'D';
    return 'F';
  }

  /**
   * Check if grade is worse
   * @param {string} currentGrade - Current grade
   * @param {string} previousGrade - Previous grade
   * @returns {boolean} True if current grade is worse
   */
  isGradeWorse(currentGrade, previousGrade) {
    const gradeOrder = ['A', 'B', 'C', 'D', 'F'];
    return gradeOrder.indexOf(currentGrade) > gradeOrder.indexOf(previousGrade);
  }

  /**
   * Get priority for queue based on severity
   * @param {string} severity - Alert severity
   * @returns {number} Priority (1=highest)
   */
  getPriority(severity) {
    switch (severity) {
      case 'Critical': return 1;
      case 'High': return 5;
      case 'Medium': return 10;
      case 'Low': return 15;
      case 'Info': return 20;
      default: return 10;
    }
  }

  /**
   * Get Slack message blocks for alert
   * @param {Object} alert - Alert object
   * @returns {Object[]} Slack blocks
   */
  getSlackBlocks(alert) {
    const colors = {
      Critical: '#c00',
      High: '#f57c00',
      Medium: '#1976d2',
      Low: '#689f38',
      Info: '#4caf50'
    };

    const emoji = {
      critical_signal: '🚨',
      score_increase: '⚠️',
      grade_degradation: '📉',
      multi_provider_confirmed: '✅',
      sync_failure: '❌'
    };

    const blocks = [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `${emoji[alert.type] || '🔔'} ${alert.severity}: ${alert.vendorName}`
        }
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Type:*\n${alert.type.replace(/_/g, ' ').toUpperCase()}`
          },
          {
            type: 'mrkdwn',
            text: `*Time:*\n${new Date(alert.createdAt).toLocaleString()}`
          }
        ]
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `<!here> ${alert.severity} severity alert for *${alert.vendorName}*`
          }
        ]
      }
    ];

    // Add alert-specific details
    if (alert.type === 'critical_signal' && alert.data.signals) {
      const signals = alert.data.signals.slice(0, 3); // Show max 3
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Critical Signals (${signals.length})*:\n${signals.map(s => `• ${s.sourceName}: ${s.description || 'N/A'}`).join('\n')}`
        }
      });
    }

    if (alert.type === 'score_increase') {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Risk Score Change:* ${alert.data.previous} → ${alert.data.current} (+${alert.data.change} points)`
        }
      });
    }

    if (alert.type === 'grade_degradation') {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Grade Change:* ${alert.data.from} → ${alert.data.to}`
        }
      });
    }

    if (alert.type === 'multi_provider_confirmed' && alert.data.issues) {
      const issues = alert.data.issues.slice(0, 3);
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Confirmed Issues (${issues.length})*:\n${issues.map(i => `• ${i.category}: ${i.providers.join(', ')}`).join('\n')}`
        }
      });
    }

    // Add action buttons
    blocks.push({
      type: 'actions',
      elements: [
        {
          type: 'button',
          text: {
            type: 'plain_text',
            text: 'View Vendor',
            emoji: true
          },
          url: `${this.frontendUrl}/vendors/${alert.data.vendorId}`,
          style: 'primary'
        },
        {
          type: 'button',
          text: {
            type: 'plain_text',
            text: 'Acknowledge',
            emoji: true
          },
          url: `${this.frontendUrl}/alerts/${alert.id}/acknowledge`,
          style: 'default'
        }
      ]
    });

    return blocks;
  }

  /**
   * Create sync failure digest
   * @param {string} organizationId - Organization ID
   * @param {Object[]} failures - Array of sync failures
   * @returns {Promise<Object>} Created alert
   */
  async createSyncFailureDigest(organizationId, failures) {
    if (failures.length === 0) {
      logger.info('No sync failures to digest', { organizationId });
      return null;
    }

    const alert = {
      organizationId,
      vendorId: null, // Not specific to one vendor
      vendorName: 'Multiple Vendors',
      type: 'sync_failure',
      severity: 'Medium',
      message: `Daily digest: ${failures.length} sync failure(s) detected`,
      data: {
        failures: failures.map(f => ({
          vendorName: f.vendor_name || 'Unknown',
          vendorId: f.vendor_id,
          connectorType: f.connector_type,
          error: f.error_message || 'Unknown error',
          failedAt: f.failed_at
        }))
      },
      createdAt: new Date()
    };

    const createdAlert = await Alert.create(alert);

    await addJob(ALERT_JOB_TYPE, createdAlert, {
      priority: this.getPriority(createdAlert.severity),
      attempts: 3,
      backoff: { type: 'exponential', delay: 1000 }
    });

    logger.info('Sync failure digest created', {
      alertId: createdAlert.id,
      failureCount: failures.length
    });

    return createdAlert;
  }
}

module.exports = AlertService;
