'use strict';

/**
 * ExecutiveSummaryService — intake-driven, LLM-generated executive summary.
 *
 *   build_executive_summary(intake, assessment) -> structured blocks
 *     { context, posture, key_risks[], quick_wins[], path_forward }
 *
 * The summary is generated by Claude from (a) the Organization Intake profile
 * and (b) the assessment scores/findings, tailored to THIS organization.
 *
 * Guardrails (consulting-grade):
 *   - Grounded ONLY in the provided intake + assessment; never invents facts.
 *   - Missing intake fields are omitted, never fabricated; sparse intake
 *     degrades to a generic-but-accurate summary.
 *   - Structured (discrete blocks) for stable layout; low temperature.
 *   - Generated text is STORED for consultant review/edit before the report is
 *     finalized — it is never auto-published. The report renderer reads the
 *     stored (reviewed) summary, or a deterministic one; it never auto-calls the
 *     LLM at render time.
 */

const db = require('../utils/db');
const logger = require('../utils/logger');
const { loadIntake } = require('./intakeProfile');

function band(s) { return s >= 80 ? 'Strong' : s >= 60 ? 'Moderate' : s >= 40 ? 'Weak' : 'Critical'; }

// Normalize dashboard data (+ frameworks) into the assessment facts we ground on.
function assessmentFrom(d, fw) {
  d = d || {};
  const p = d.overallPosture || {};
  const dm = Array.isArray(d.domainMatrix) ? d.domainMatrix : [];
  const strengths = [...dm].sort((a, b) => b.current - a.current).slice(0, 3)
    .map((x) => ({ name: x.name, score: x.current, status: x.status }));
  const weakest = [...dm].sort((a, b) => a.current - b.current).slice(0, 3)
    .map((x) => ({ name: x.name, score: x.current, status: x.status, deteriorating: x.topDeteriorating && x.topDeteriorating.metric }));
  const topActions = (d.actionQueue || []).slice(0, 5)
    .map((a) => ({ action: a.action, owner: a.owner, due: a.dueDate, process: a.process, escalate: !!a.escalation }));
  const out = {
    overall: { score: p.current, band: band(p.current || 0), trend: p.trend, delta: p.delta },
    strengths, weakest, topActions, controlCount: (d.controlRisk || []).length,
  };
  if (d.thresholds) out.thresholds = { breaches: d.thresholds.breaches, total: d.thresholds.total, critical: d.thresholds.critical };
  if (fw) {
    const f = {};
    if (fw.csf) f.csf = { overall: fw.csf.overall };
    if (fw.nist80053 && fw.nist80053.baseline) f.nist80053 = { baseline: fw.nist80053.baseline.name, coveragePct: fw.nist80053.baseline.coveragePct };
    if (fw.attack && fw.attack.summary) f.attack = { covered: fw.attack.summary.covered, total: fw.attack.summary.total };
    if (Object.keys(f).length) out.frameworks = f;
  }
  return out;
}

// ---- deterministic fallback — accurate, grounded, no fabrication --------------
function deterministic(intake, a) {
  intake = intake || {}; a = a || { overall: {} };
  const op = intake.org_profile || {}, tech = intake.technology || {}, proc = intake.process || {};
  const name = intake.client_name || 'The organization';
  const regs = op.regulatory_obligations || [];
  const jewels = op.crown_jewels || [];

  const ctx = [];
  ctx.push(op.industry ? `${name} operates in ${op.industry}${op.sub_sector ? ` (${op.sub_sector})` : ''}` : `${name}`);
  if (op.employee_count) ctx.push(`with approximately ${op.employee_count} employees`);
  if (op.revenue_band) ctx.push(`and revenue in the ${op.revenue_band} band`);
  let context = ctx.join(' ').trim() + '.';
  if (regs.length) context += ` It is subject to ${regs.join(', ')}, which set the baseline for its security obligations.`;
  if ((op.geos || []).length) context += ` Operations span ${op.geos.join(', ')}.`;

  let posture = `Overall cybersecurity posture is ${a.overall.score != null ? a.overall.score : '—'}/100 (${a.overall.band})${a.overall.trend ? `, ${a.overall.trend}` : ''}, assessed across ${a.controlCount || 0} control areas through NIST CSF 2.0, NIST SP 800-53, and MITRE ATT&CK.`;
  if (a.thresholds && a.thresholds.breaches) posture += ` ${a.thresholds.breaches} of ${a.thresholds.total} risk-appetite thresholds are breached (${a.thresholds.critical} critical).`;
  if (jewels.length && (a.weakest || []).length) posture += ` Weakness in ${a.weakest[0].name} bears directly on ${jewels.slice(0, 2).join(' and ')}.`;
  else if (regs.length && (a.weakest || []).length) posture += ` ${a.weakest[0].name} is the most exposed area relative to ${regs[0]} obligations.`;

  const key_risks = (a.weakest || []).map((w) => ({
    title: w.name,
    detail: `${w.name} scores ${w.score}/100 (${w.status})${w.deteriorating ? `; ${w.deteriorating} is deteriorating` : ''}.${regs.length ? ` Material to ${regs[0]} obligations.` : ''}`,
  }));

  const quick_wins = (a.topActions || []).slice(0, 4).map((t) => ({
    title: t.action,
    detail: `Owner ${t.owner || 'TBD'}, due ${t.due || 'TBD'}${t.process ? `; protects ${t.process}` : ''}.`,
  }));

  let path_forward = 'The path to target state sequences the highest-risk control families first, then closes breached risk-appetite thresholds while sustaining the areas already improving. ';
  if (proc.incident_response && /no|immature|partial|none/i.test(String(proc.incident_response))) {
    path_forward += 'Given current incident-response maturity, elevating Respond and Recover capabilities is recommended early. ';
  }
  if (tech.hosting || (tech.key_platforms || []).length || tech.app_count) {
    path_forward += `The ${tech.hosting || 'current'} environment${tech.app_count ? ` with roughly ${tech.app_count} applications` : ''} makes identity governance and configuration baselines high-leverage investments. `;
  }
  path_forward += 'Executed over the coming quarters, this roadmap moves the organization toward a defensible, obligation-aligned posture.';

  return { context, posture, key_risks, quick_wins, path_forward, generatedBy: 'deterministic', model: null };
}

function normalizeBlocks(j, by, model) {
  const asArr = (v) => (Array.isArray(v) ? v : []).map((x) => (typeof x === 'string' ? { title: x, detail: '' } : { title: String(x.title || ''), detail: String(x.detail || '') })).filter((x) => x.title);
  return {
    context: String(j.context || '').trim(),
    posture: String(j.posture || '').trim(),
    key_risks: asArr(j.key_risks),
    quick_wins: asArr(j.quick_wins),
    path_forward: String(j.path_forward || '').trim(),
    generatedBy: by,
    model,
  };
}

async function llm(intake, a) {
  const Anthropic = require('@anthropic-ai/sdk');
  const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const model = process.env.ANTHROPIC_SUMMARY_MODEL || 'claude-opus-4-8';
  const system = [
    'You are a senior cybersecurity consultant writing the executive summary of a posture assessment for a board / C-suite audience.',
    'Tone: professional, concise, decisive — no hedging filler.',
    'GROUND every statement ONLY in the JSON provided (intake + assessment). Do NOT invent facts about the client, their breaches, or their environment.',
    'If an intake field is missing, omit that claim — never fabricate a value. If intake is sparse, write a generic-but-accurate summary from the assessment data.',
    'Return ONLY JSON with keys:',
    ' context: 2-3 sentences of organizational context (sector, size, regulatory drivers) from org_profile.',
    ' posture: frame the overall posture and headline score in terms of the org\'s specific business risk and obligations.',
    ' key_risks: array of 3-5 objects {title, detail} — the highest-priority findings with business impact.',
    ' quick_wins: array of objects {title, detail} — high-leverage near-term actions.',
    ' path_forward: one forward-looking paragraph on the path to target state.',
  ].join('\n');
  const user = `INTAKE:\n${JSON.stringify(intake)}\n\nASSESSMENT:\n${JSON.stringify(a)}`;
  // No `temperature`: it is rejected (400) on claude-opus-4-8 and the rest of the
  // 4.7+ family. (Previously set to 0.2, which silently forced the deterministic
  // fallback on every call.) Steer with the prompt instead.
  const resp = await client.messages.create({
    model, max_tokens: 1600,
    system, messages: [{ role: 'user', content: user }],
  });
  const raw = (resp.content || []).map((c) => c.text || '').join('');
  const json = JSON.parse(raw.slice(raw.indexOf('{'), raw.lastIndexOf('}') + 1));
  return normalizeBlocks(json, 'llm', resp.model || model);
}

// build_executive_summary(intake, assessment) -> structured blocks
async function buildExecutiveSummary(intake, assessment) {
  if (process.env.ANTHROPIC_API_KEY) {
    try { return await llm(intake, assessment); }
    catch (e) { logger.debug('exec summary LLM fell back to deterministic', { error: e.message }); }
  }
  return deterministic(intake, assessment);
}

// ---- persistence (human-in-the-loop) -----------------------------------------
async function getStored(orgId) {
  const r = await db.query('SELECT * FROM exec_summaries WHERE org_id=$1', [orgId]);
  if (!r[0]) return null;
  const row = r[0];
  const blocks = typeof row.blocks === 'string' ? JSON.parse(row.blocks) : row.blocks;
  return { blocks, status: row.status, model: row.model, generatedBy: row.generated_by, generatedAt: row.generated_at, updatedAt: row.updated_at, editedBy: row.edited_by };
}

async function store(orgId, blocks, { status = 'draft', editedBy = null } = {}) {
  await db.query(
    `INSERT INTO exec_summaries (id, org_id, blocks, status, model, generated_by, generated_at, updated_at, edited_by)
     VALUES ($1,$2,$3,$4,$5,$6,NOW(),NOW(),$7)
     ON CONFLICT (org_id) DO UPDATE SET
       blocks=EXCLUDED.blocks, status=EXCLUDED.status, model=EXCLUDED.model,
       generated_by=EXCLUDED.generated_by, updated_at=NOW(), edited_by=EXCLUDED.edited_by`,
    [`es_${orgId}`, orgId, JSON.stringify(blocks), status, blocks.model || null, blocks.generatedBy || null, editedBy]);
  return getStored(orgId);
}

// Explicit generation → stored as a DRAFT for consultant review (not published).
async function generate(orgId, d, fw) {
  const intake = await loadIntake(orgId);
  const assessment = assessmentFrom(d, fw);
  const blocks = await buildExecutiveSummary(intake, assessment);
  return store(orgId, blocks, { status: 'draft' });
}

// Consultant saves their reviewed/edited version.
async function saveEdited(orgId, blocks, editedBy) {
  return store(orgId, normalizeBlocks(blocks, 'edited', blocks.model || null), { status: 'reviewed', editedBy: editedBy || null });
}

// What the report renders: the stored (reviewed/draft) summary if present,
// otherwise a deterministic one from data. Never auto-calls the LLM.
async function forReport(orgId, d, fw) {
  const stored = await getStored(orgId);
  if (stored && stored.blocks) return { ...stored.blocks, status: stored.status, stored: true };
  const intake = await loadIntake(orgId);
  return { ...deterministic(intake, assessmentFrom(d, fw)), status: 'auto', stored: false };
}

module.exports = { buildExecutiveSummary, assessmentFrom, deterministic, generate, getStored, saveEdited, forReport };
