'use strict';

/**
 * SampleDocService — PILOT/TEST sample-document generator (flag-gated).
 *
 * For a requested manual-control document_type, generates a representative
 * document whose sections echo each mapped control's requirement, so testers/
 * pilot users can run the full intake → normalize → review → fan-out pipeline
 * end-to-end. Every sample is clearly labeled as a TEST FIXTURE.
 *
 * Gated by PILOT_SAMPLE_DOCS=true. Deterministic (no LLM needed).
 */

const db = require('../utils/db');

const slug = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'sample';

function isPilot() { return process.env.PILOT_SAMPLE_DOCS === 'true'; }

const BANNER = 'SAMPLE / TEST FIXTURE — generated by CyberRx pilot mode. Not a real control document.';

// Pure: build representative document text from the type + its mapped controls.
function buildSampleText(docType, controls) {
  const L = [];
  L.push(BANNER);
  L.push('');
  L.push(docType.name);
  if (docType.category) L.push(`Document type: ${docType.category}`);
  L.push('');
  L.push('1. Purpose');
  L.push(`This ${docType.name} establishes how the organization manages the controls below. ${docType.description || ''}`.trim());
  L.push('');
  L.push('2. Scope');
  L.push('This document applies to all systems, personnel, contractors, and third parties acting on behalf of the organization.');
  L.push('');
  L.push('3. Policy and Procedures');
  (controls || []).forEach((c, i) => {
    const req = c.expected_requirement || c.requirement_text || c.title || '';
    L.push(`3.${i + 1} ${c.title || c.requirement_id} (${c.framework_id} ${c.requirement_id})`);
    L.push(`The organization ensures the following is established, documented, communicated, and maintained: ${req}`);
  });
  L.push('');
  L.push('4. Roles and Responsibilities');
  L.push('Management approves this document; the security team maintains it; all personnel are required to comply.');
  L.push('');
  L.push('5. Review and Maintenance');
  L.push('This document is reviewed and approved at least annually and after any significant change.');
  L.push('');
  L.push(BANNER);
  return L.join('\n');
}

async function generateForType(documentTypeId) {
  const dt = (await db.query('SELECT id, name, description, category FROM document_type WHERE id=$1', [documentTypeId]))[0];
  if (!dt) throw new Error(`unknown document_type: ${documentTypeId}`);
  const controls = await db.query(
    `SELECT m.framework_id, m.requirement_id, m.expected_requirement, r.title, r.text AS requirement_text
       FROM document_control_map m
       JOIN framework_requirements r ON r.framework_id = m.framework_id AND r.requirement_id = m.requirement_id
      WHERE m.document_type_id = $1`, [documentTypeId]);
  const text = buildSampleText(dt, controls);
  return { documentTypeId, fileName: `SAMPLE-${slug(dt.name)}.txt`, text, controlsReferenced: controls.length, sample: true };
}

module.exports = { isPilot, buildSampleText, generateForType, BANNER };
